version: 2.1
orbs:
  docker: circleci/docker@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  scan:
    executor:
      name: docker/docker
    working_directory: /home/circleci/openapi-graph-extractor
    steps:
      - attach_workspace:
          at: /home/circleci/
      - sonarcloud/scan
  test:
    docker:
      - image: denoland/deno:1.38.3
    working_directory: /home/circleci/openapi-graph-extractor
    steps:
      - checkout
      - run:
            name: Deno Test and Coverage Report
            command: |
              deno cache --reload --lock=deno.lock cli.ts 
              deno test --coverage=coverage
              deno coverage coverage --lcov --output=coverage/lcov.info
      - persist_to_workspace:
            root: /home/circleci/
            paths:
              - openapi-graph-extractor
              - openapi-graph-extractor/tests/test-results
      - store_artifacts:
          path: /home/circleci/openapi-graph-extractor
      - store_test_results:
          path: /home/circleci/openapi-graph-extractor/tests/test-results
workflows:
    version: 2
    test_and_scan:
      jobs:
        - test:
            post-steps:
              - persist_to_workspace:
                  root: /home/circleci/
                  paths:
                    - openapi-graph-extractor
            context:
                - DockerHub
        - scan:
            requires:
              - test
            context:
              - SonarCloud